{{- if and .Values.mongodb.enabled .Values.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "logquickwit.fullname" . }}-mongodb-data-pvc
  labels:
    app: mongodb
    {{- include "logquickwit.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.mongodb.persistence.accessMode }}
  storageClassName: {{ .Values.mongodb.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "logquickwit.fullname" . }}-mongodb-config-pvc
  labels:
    app: mongodb
    {{- include "logquickwit.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.mongodb.persistence.accessMode }}
  storageClassName: {{ .Values.mongodb.persistence.storageClass }}
  resources:
    requests:
      storage: 1Gi
{{- end }}