{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "central-logging.fullname" . }}-mongodb
  labels:
    app: mongodb
    {{- include "central-logging.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          resources:
          {{- toYaml .Values.mongodb.resources | nindent 10 }}
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: {{ include "central-logging.fullname" . }}-mongodb-pvc
{{- end }}