{{- if and .Values.mongodb.enabled .Values.mongodb.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logquickwit.fullname" . }}-mongodb-secret
  labels:
    app: mongodb
    {{- include "logquickwit.labels" . | nindent 4 }}
type: Opaque
stringData:
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | quote }}
{{- end }}